# Generated by Django 6.0.2 on 2026-02-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_file_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='ff0000', max_length=6),
            preserve_default=False,
        ),
    ]
